### PR TITLE
Enable promises behind a feature

### PR DESCRIPTION
**Pull request by jeffcharles**
The feature is off by default. It can be enabled by running `make cli CORE_FEATURES=experimental_event_loop` and tests can be run by invoking `make test-cli CORE_FEATURES=experimental_event_loop CLI_FEATURES=experimental_event_loop`.

### CODE REVIEW

**Comment by surma** [comment]
[Simplified the test runner](https://github.com/Shopify/javy/compare/surma/update-wpt?expand=1) since we can now rely on proises :D

**Comment by saulecabrera** [comment]
I left an offline note to @jeffcharles, but I'll add here too for visibility: before landing this I'd like for us to ensure that unhandled rejected promises are behaving correctly, a preliminary test on my end shows that the current behaviour doesn't throw, which  is wrong afaik. So we might have to fix that.

**Comment by surma** [comment]
This is probably also a reminder that we should run [test262](https://github.com/tc39/test262)

**Comment by jeffcharles** [comment]
Discussed offline, we're going to put this behind a default off feature for now

**Pull request merged**
